version = 1

test_patterns = ["test/**"]

exclude_patterns = ["dist/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  dialect = "typescript"
  environment = ["jest"]
  style_guide = "standard"
